/**
 * contract.ts — Embedding Space Contract & Fingerprinting
 *
 * Enforces strict embedding-space identity so that vectors generated by
 * different models, tokenizers, pooling strategies, query prefixes, or
 * dimensions are never silently mixed or corrupted in SQLite vector indexes.
 */

import { createHash } from "crypto";

export type EmbeddingBackendType = "mlx" | "gguf";

export type PoolingStrategy = "mean" | "cls" | "last_token" | "none";

export interface EmbeddingDescriptor {
  version: 1;
  backend: EmbeddingBackendType;
  model: string;
  revision?: string;
  tokenizer?: string;
  pooling: PoolingStrategy;
  queryPrefix?: string;
  docPrefix?: string;
  nativeDimensions: number;
  outputDimensions: number;
  maxTokens: number;
  normalized: boolean;
  dtype?: string;
  quantization?: string;
}

/**
 * Computes a deterministic SHA-256 fingerprint of the embedding space geometry.
 * Any difference in model, revision, pooling, prefixes, dimensions, or normalization
 * produces a completely different space ID.
 */
export function computeEmbeddingSpaceId(descriptor: EmbeddingDescriptor): string {
  // Normalize fields that define vector space geometry
  const canonical = {
    v: descriptor.version,
    b: descriptor.backend,
    m: descriptor.model.trim(),
    t: descriptor.tokenizer?.trim() || "",
    r: descriptor.revision?.trim() || "",
    p: descriptor.pooling,
    qp: descriptor.queryPrefix || "",
    dp: descriptor.docPrefix || "",
    nd: descriptor.nativeDimensions,
    od: descriptor.outputDimensions,
    n: descriptor.normalized,
    dt: descriptor.dtype?.trim() || "",
    q: descriptor.quantization?.trim() || "",
  };

  const json = JSON.stringify(canonical, Object.keys(canonical).sort());
  return createHash("sha256").update(json).digest("hex").slice(0, 24);
}

/**
 * Validates that two embedding descriptors represent identical vector spaces.
 */
export function areDescriptorsCompatible(
  expected: EmbeddingDescriptor,
  actual: EmbeddingDescriptor,
): boolean {
  if (expected.outputDimensions !== actual.outputDimensions) return false;
  if (expected.normalized !== actual.normalized) return false;
  if (expected.pooling !== actual.pooling) return false;
  
  const id1 = computeEmbeddingSpaceId(expected);
  const id2 = computeEmbeddingSpaceId(actual);
  return id1 === id2;
}

/**
 * Throws an actionable error if the actual descriptor does not match the expected one.
 */
export function assertEmbeddingCompatibility(
  expected: EmbeddingDescriptor,
  actual: EmbeddingDescriptor,
  context?: string,
): void {
  if (areDescriptorsCompatible(expected, actual)) return;

  const prefix = context ? `[${context}] ` : "";
  const expId = computeEmbeddingSpaceId(expected);
  const actId = computeEmbeddingSpaceId(actual);

  throw new Error(
    `${prefix}Embedding space mismatch: index uses model '${expected.model}' (${expected.outputDimensions}d, space: ${expId}), ` +
    `but current runtime resolved to '${actual.model}' (${actual.outputDimensions}d, space: ${actId}). ` +
    `Cannot mix embedding spaces. Run with the matching model or re-index with --rebuild.`
  );
}

/**
 * Checks if a model name is a Qwen3/Qwen2 embedding model.
 */
export function isQwenEmbeddingModel(modelName: string): boolean {
  return /qwen.*embed/i.test(modelName) || /embed.*qwen/i.test(modelName);
}

/**
 * Checks if a model name is a Nomic embedding model.
 */
export function isNomicEmbeddingModel(modelName: string): boolean {
  return /nomic/i.test(modelName);
}

/**
 * Formats a query string for embedding according to model requirements.
 */
export function formatQueryForDescriptor(query: string, descriptor: Partial<EmbeddingDescriptor>): string {
  if (descriptor.queryPrefix !== undefined) {
    return `${descriptor.queryPrefix}${query}`;
  }
  const model = descriptor.model || "";
  if (isQwenEmbeddingModel(model)) {
    return `Instruct: Retrieve relevant documents for the given query\nQuery: ${query}`;
  }
  if (isNomicEmbeddingModel(model)) {
    return `search_query: ${query}`;
  }
  // Default embeddinggemma format
  return `task: search result | query: ${query}`;
}

/**
 * Formats a document chunk for embedding according to model requirements.
 */
export function formatDocForDescriptor(text: string, title?: string, descriptor?: Partial<EmbeddingDescriptor>): string {
  if (descriptor?.docPrefix !== undefined) {
    return `${descriptor.docPrefix}${text}`;
  }
  const model = descriptor?.model || "";
  if (isQwenEmbeddingModel(model)) {
    return title ? `${title}\n${text}` : text;
  }
  if (isNomicEmbeddingModel(model)) {
    return title ? `search_document: ${title}\n${text}` : `search_document: ${text}`;
  }
  // Default embeddinggemma format
  return `title: ${title || "none"} | text: ${text}`;
}
